version: "3.7"

services:
  mysql-service:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - red_parcial_swarm

  service-nodejs:
    image: rest
    deploy:
      replicas: 1
    command: >
      sh -c "while ! nc -z mysql 3306; do sleep 1; done; node index.js"
    ports:
      - "8080:8080"
    networks:
      - red_parcial_swarm

  service-soap:
    image: soap
    deploy:
      replicas: 1
    command: >
      sh -c "while ! nc -z mysql 3306; do sleep 1; done; node index.js"
    ports:
      - "8888:8888"
    networks:
      - red_parcial_swarm

  service-cliente:
    image: front
    ports:
      - "8081:8081"
    deploy:
      replicas: 4
    networks:
      - red_parcial_swarm

networks:
  red_parcial_swarm: