version: '3.7'

services:
  mysql:
    image: mysql-image
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
        - mynetwork
    deploy:
      replicas: 1 

  service-nodejs:
    image: rest
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    deploy:
      replicas: 1 

  service-soap:
    image: soap
    ports:
      - "8888:8888"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  service-cliente   :
    image: cliente
    ports:
      - "8081:80"
    networks:
      - mynetwork
    deploy:
      replicas: 4 
  
  

networks:
  mynetwork:
